-- MySQL Script generated by MySQL Workbench
-- Tue Aug 27 16:39:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sis_matricula
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sis_matricula
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sis_matricula` DEFAULT CHARACTER SET utf8 ;
USE `sis_matricula` ;

-- -----------------------------------------------------
-- Table `sis_matricula`.`AlunoStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`AlunoStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_matricula`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`Aluno` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `periodo` VARCHAR(45) NOT NULL,
  `data_ingresso` DATE NOT NULL,
  `AlunoStatus_id` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_Aluno_AlunoStatus1_idx` (`AlunoStatus_id` ASC),
  CONSTRAINT `fk_Aluno_AlunoStatus1`
    FOREIGN KEY (`AlunoStatus_id`)
    REFERENCES `sis_matricula`.`AlunoStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_matricula`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` CHAR(15) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `telefone` CHAR(15) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `Aluno_matricula` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuario_Aluno1_idx` (`Aluno_matricula` ASC),
  CONSTRAINT `fk_Usuario_Aluno1`
    FOREIGN KEY (`Aluno_matricula`)
    REFERENCES `sis_matricula`.`Aluno` (`matricula`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_matricula`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`Curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `duracao` INT NOT NULL,
  `creditos` INT NOT NULL,
  `carga_horaria` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_matricula`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`Disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `carga_horaria` VARCHAR(255) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_matricula`.`Mensalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`Mensalidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mes` CHAR(2) NOT NULL,
  `ano` CHAR(4) NOT NULL,
  `data_validade` DATE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `Aluno_matricula` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Mensalidade_Aluno1_idx` (`Aluno_matricula` ASC),
  CONSTRAINT `fk_Mensalidade_Aluno1`
    FOREIGN KEY (`Aluno_matricula`)
    REFERENCES `sis_matricula`.`Aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_matricula`.`MensalidadeStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`MensalidadeStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `Mensalidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MensalidadeStatus_Mensalidade1_idx` (`Mensalidade_id` ASC),
  CONSTRAINT `fk_MensalidadeStatus_Mensalidade1`
    FOREIGN KEY (`Mensalidade_id`)
    REFERENCES `sis_matricula`.`Mensalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_matricula`.`Notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`Notificacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(1000) NOT NULL,
  `Aluno_matricula` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Notificacao_Aluno1_idx` (`Aluno_matricula` ASC),
  CONSTRAINT `fk_Notificacao_Aluno1`
    FOREIGN KEY (`Aluno_matricula`)
    REFERENCES `sis_matricula`.`Aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_matricula`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`Funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `salario` DOUBLE NOT NULL,
  `data_admissao` DATE NOT NULL,
  `Usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Funcionarios_Usuario_idx` (`Usuario_id` ASC),
  CONSTRAINT `fk_Funcionarios_Usuario`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `sis_matricula`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_matricula`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`Cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `Funcionarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cargo_Funcionarios1_idx` (`Funcionarios_id` ASC),
  CONSTRAINT `fk_Cargo_Funcionarios1`
    FOREIGN KEY (`Funcionarios_id`)
    REFERENCES `sis_matricula`.`Funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_matricula`.`Curso_Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`Curso_Aluno` (
  `Curso_id` INT NOT NULL,
  `Aluno_matricula` INT NOT NULL,
  `periodo` INT NOT NULL,
  `aproveitamento` FLOAT NULL,
  PRIMARY KEY (`Curso_id`, `Aluno_matricula`),
  INDEX `fk_Curso_has_Aluno_Aluno1_idx` (`Aluno_matricula` ASC),
  INDEX `fk_Curso_has_Aluno_Curso1_idx` (`Curso_id` ASC),
  CONSTRAINT `fk_Curso_has_Aluno_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `sis_matricula`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_matricula`)
    REFERENCES `sis_matricula`.`Aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_matricula`.`Aluno_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`Aluno_Disciplina` (
  `Aluno_matricula` INT NOT NULL,
  `Disciplina_id` INT NOT NULL,
  `nota` DOUBLE NOT NULL,
  `frequencia` FLOAT NOT NULL,
  PRIMARY KEY (`Aluno_matricula`, `Disciplina_id`),
  INDEX `fk_Aluno_has_Disciplina_Disciplina1_idx` (`Disciplina_id` ASC),
  INDEX `fk_Aluno_has_Disciplina_Aluno1_idx` (`Aluno_matricula` ASC),
  CONSTRAINT `fk_Aluno_has_Disciplina_Aluno1`
    FOREIGN KEY (`Aluno_matricula`)
    REFERENCES `sis_matricula`.`Aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_id`)
    REFERENCES `sis_matricula`.`Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sis_matricula`.`Mensalidade_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_matricula`.`Mensalidade_Disciplina` (
  `Mensalidade_id` INT NOT NULL,
  `Disciplina_id` INT NOT NULL,
  PRIMARY KEY (`Mensalidade_id`, `Disciplina_id`),
  INDEX `fk_Mensalidade_has_Disciplina_Disciplina1_idx` (`Disciplina_id` ASC),
  INDEX `fk_Mensalidade_has_Disciplina_Mensalidade1_idx` (`Mensalidade_id` ASC),
  CONSTRAINT `fk_Mensalidade_has_Disciplina_Mensalidade1`
    FOREIGN KEY (`Mensalidade_id`)
    REFERENCES `sis_matricula`.`Mensalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensalidade_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_id`)
    REFERENCES `sis_matricula`.`Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

